In [1]:
import numpy as np
import numpy.linalg as la
from sympy import *

In [5]:
X = np.array([[1,0],[0,1],[0,0]])

In [9]:
XT = np.array([[0],[0],[1]])

In [14]:
X.T @ XT

array([[0],
       [0]])

In [36]:
def com(omega,p):

	return np.dot(omega,p) - np.dot(p,omega)

In [1254]:
a = np.array([[1,2,1],[0,1,0],[0,0,-1]])

In [1255]:
a.T @ a

array([[1, 2, 1],
       [2, 5, 2],
       [1, 2, 2]])

Optimize the function
$$ f(x,y,z) = z$$

In [1166]:
x = np.random.rand(2)

In [905]:
G = np.array([[ x[0]**4/4 + x[0]**2*x[1]**2/2 + x[0]**2/2 + x[1]**4/4 +x[1]**2/2 + 1/4,0],
			 [0, x[0]**4/4 + x[0]**2*x[1]**2/2 + x[0]**2/2 + x[1]**4/4 +x[1]**2/2 + 1/4,]])
J = np.array( [[4*x[0]/(x[0]**2+x[1]**2+1)**2],[4*x[1]/(x[0]**2+x[1]**2+1)**2]])
grad = (G@J).T.reshape(2)
x = x + 0.1 * grad

In [998]:
x

array([0.04206683, 0.35835239])

Optimize the function $$ f(x,y,z) = x+y $$ 

In [1161]:
G = np.array([[ x[0]**4/4 + x[0]**2*x[1]**2/2 + x[0]**2/2 + x[1]**4/4 +x[1]**2/2 + 1/4,0],
			 [0, x[0]**4/4 + x[0]**2*x[1]**2/2 + x[0]**2/2 + x[1]**4/4 +x[1]**2/2 + 1/4,]])
J = np.array([[-(2*(x[0]**2 + 2*x[0]*x[1] - x[1]**2 - 1))/(x[0]**2 + x[1]**2 + 1)**2], 
		  [-(2*(- x[0]**2 + 2*x[0]*x[1] + x[0]**2 - 1))/(x[0]**2 + x[1]**2 + 1)**2]])
grad = (G@J).T.reshape(2)
x = x + 0.1 * grad

In [1164]:
J

array([[ 0.00075567],
       [-0.00854927]])

Optimize the function $$ f(x,y,z) = x^2 -3*y + 2*z $$


In [1247]:
G = np.array([[ x[0]**4/4 + x[0]**2*x[1]**2/2 + x[0]**2/2 + x[1]**4/4 +x[1]**2/2 + 1/4,0],
			 [0, x[0]**4/4 + x[0]**2*x[1]**2/2 + x[0]**2/2 + x[1]**4/4 +x[1]**2/2 + 1/4,]])

J = np.array([[ (4*x[0]*(3*x[0]**2*x[1] + 3*x[1]**3 + 4*x[1]**2 + 3*x[1] + 4))/(x[0]**2 + x[1]**2 + 1)**3], 
		  [-(2*(3*x[0]**4 + 4*x[0]**2*x[1] + 6*x[0]**2 - 3*x[1]**4 - 4*x[1]**3 - 4*x[1] + 3))/(x[0]**2 + x[1]**2 + 1)**3]])
grad = (G@J).T.reshape(2)
x = x + 0.1 * grad

In [1248]:
x

array([ 1.92078766e-05, -1.86851709e+00])

In [1249]:
x=0
y=-3/np.sqrt(13)
z=2/np.sqrt(13)


In [1250]:
a = x/(1-z)
a

0.0

In [1251]:
b = y/(1-z)

In [1252]:
b

-1.8685170918213299

In [1]:
import numpy as np

In [2]:
J = np.array([[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])

In [4]:
J.T @ J

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

Example $ ad \Omega $ 

Take a skew-symmetric matrix, say $3x3$, and see how it acts on the $3x3$ symmetric matrices via $P \mapsto ad \Omega(P):= [\Omega,P]:= \Omega P - P \Omega$

Choose a particular $\Omega (skew)$, and see what it does to a symmetric matrix.

$ Sym_3 = R^6$, so if you wish, you can choose a basis in $Sym_3$, and find the matrix of $ad \Omega$ (should be a $6x6$ matrix)

In [2]:
omega = np.array([[0,1,-2],[-1,0,3],[2,-3,0]])
p = np.array([[1,1,-1],[1,2,0],[-1,0,5]])

In [5]:
np.dot(omega,p)-np.dot(p,omega)

array([[  6,  -2, -11],
       [ -2,  -2,  12],
       [-11,  12,  -4]])

In [23]:
np.dot(omega,p).T

array([[  3,  -4,  -1],
       [  2,  -1,  -4],
       [-10,  16,  -2]])

In [24]:
np.dot(p,omega)

array([[ -3,   4,   1],
       [ -2,   1,   4],
       [ 10, -16,   2]])

In [20]:
np.tensordot(np.array([0,1,-2,0,3,0]),np.array([0,-1,2,0,-3,0]),-1)

array([[ 0,  0,  0,  0,  0,  0],
       [ 0, -1,  2,  0, -3,  0],
       [ 0,  2, -4,  0,  6,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0, -3,  6,  0, -9,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [38]:
O = np.array([[0, -1, 2, -1, 0, 0, 2, 2, 0],
		  [2, 0, -3, 0, -2, 2, -3, 0, 0],
		  [-4, 3, 0, 3, 0, -1, 0, -1, 4],
		  [0, 1, 0, 1, 0, -3, 0, -3, 0],
		  [0, -2, 1, -2, 6, 0, 1, 0, 6],
		  [0, 0, -2, 0, 0, 3, -2, 3, 0]])

In [39]:
O

array([[ 0, -1,  2, -1,  0,  0,  2,  2,  0],
       [ 2,  0, -3,  0, -2,  2, -3,  0,  0],
       [-4,  3,  0,  3,  0, -1,  0, -1,  4],
       [ 0,  1,  0,  1,  0, -3,  0, -3,  0],
       [ 0, -2,  1, -2,  6,  0,  1,  0,  6],
       [ 0,  0, -2,  0,  0,  3, -2,  3,  0]])

In [40]:
np.dot(np.array([1,1,-1,2,0,5]),O)

array([  6,  -2, -11,  -2,  -2,  12, -11,  12,  -4])

In [61]:
G = np.array([O[:,0],O[:,1],O[:,2],O[:,3],O[:,5],O[:,8]]).T

In [62]:
np.dot(np.array([1,1,-1,2,0,5]),G)

array([  6,  -2, -11,  -2,  12,  -4])

In [63]:
G

array([[ 0, -1,  2, -1,  0,  0],
       [ 2,  0, -3,  0,  2,  0],
       [-4,  3,  0,  3, -1,  4],
       [ 0,  1,  0,  1, -3,  0],
       [ 0, -2,  1, -2,  0,  6],
       [ 0,  0, -2,  0,  3,  0]])

In [73]:
G = np.array([[0,2,-4,0,0,0],
			  [-1,0,3,1,-2,0],
			  [2,-3,0,0,1,-2],
			  [0,-2,0,0,6,0],
			  [0,2,-1,-3,0,3],
			  [0,0,4,0,-6,0]])

In [74]:
np.dot(G,np.array([1,1,-1,2,0,5]))

array([  6,  -2, -11,  -2,  12,  -4])

Proposition about the tangent space to the Grassmanian:
$T_P G$ consists of all commutators $[P, \Omega]$, for $\Omega$ - skew, $P \in G$ (symmetric, idempotent, rank $k$ for $G(k,n)). Choose small $k$ and $n$, e.g., ($k=1, n=3$), ($k=2, n=3$), ($k=2, n=4)$ and for each of these take a particular $P \in G$ and describe $T_P G$. It should consists of some particular symmetric $3 \times 3$ ( in the first 2 cases) and $4 \times 4$ (in the last case) matrices, that form the tangent space to the grassmannian at $P$. For starters, you can take some simple $P$ in each case, e.g., with many zeros

In [27]:
T = np.array([[1,1,1],[1,1,1],[0,0,0]])

In [28]:
np.linalg.matrix_rank(T)

1

In [29]:
np.dot(T,T)

array([[2, 2, 2],
       [2, 2, 2],
       [0, 0, 0]])

In [34]:
V = np.array([[0,1,-2],
			  [-1,0,3],
			  [2,-3,0]])
np.linalg.matrix_rank(V)

2

In [42]:
V = np.array([[1,0,0],
			  [0,1,0],
			  [0,0,0]])
np.linalg.matrix_rank(V)
np.dot(V,V)
V.T

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 0]])