In [1253]:
import numpy as np
import numpy.linalg as la
from sympy import *

In [1254]:
a = np.array([[1,2,1],[0,1,0],[0,0,-1]])

In [1255]:
a.T @ a

array([[1, 2, 1],
       [2, 5, 2],
       [1, 2, 2]])

Optimize the function
$$ f(x,y,z) = z$$

In [1166]:
x = np.random.rand(2)

In [905]:
G = np.array([[ x[0]**4/4 + x[0]**2*x[1]**2/2 + x[0]**2/2 + x[1]**4/4 +x[1]**2/2 + 1/4,0],
			 [0, x[0]**4/4 + x[0]**2*x[1]**2/2 + x[0]**2/2 + x[1]**4/4 +x[1]**2/2 + 1/4,]])
J = np.array( [[4*x[0]/(x[0]**2+x[1]**2+1)**2],[4*x[1]/(x[0]**2+x[1]**2+1)**2]])
grad = (G@J).T.reshape(2)
x = x + 0.1 * grad

In [998]:
x

array([0.04206683, 0.35835239])

Optimize the function $$ f(x,y,z) = x+y $$ 

In [1161]:
G = np.array([[ x[0]**4/4 + x[0]**2*x[1]**2/2 + x[0]**2/2 + x[1]**4/4 +x[1]**2/2 + 1/4,0],
			 [0, x[0]**4/4 + x[0]**2*x[1]**2/2 + x[0]**2/2 + x[1]**4/4 +x[1]**2/2 + 1/4,]])
J = np.array([[-(2*(x[0]**2 + 2*x[0]*x[1] - x[1]**2 - 1))/(x[0]**2 + x[1]**2 + 1)**2], 
		  [-(2*(- x[0]**2 + 2*x[0]*x[1] + x[0]**2 - 1))/(x[0]**2 + x[1]**2 + 1)**2]])
grad = (G@J).T.reshape(2)
x = x + 0.1 * grad

In [1164]:
J

array([[ 0.00075567],
       [-0.00854927]])

Optimize the function $$ f(x,y,z) = x^2 -3*y + 2*z $$


In [1247]:
G = np.array([[ x[0]**4/4 + x[0]**2*x[1]**2/2 + x[0]**2/2 + x[1]**4/4 +x[1]**2/2 + 1/4,0],
			 [0, x[0]**4/4 + x[0]**2*x[1]**2/2 + x[0]**2/2 + x[1]**4/4 +x[1]**2/2 + 1/4,]])

J = np.array([[ (4*x[0]*(3*x[0]**2*x[1] + 3*x[1]**3 + 4*x[1]**2 + 3*x[1] + 4))/(x[0]**2 + x[1]**2 + 1)**3], 
		  [-(2*(3*x[0]**4 + 4*x[0]**2*x[1] + 6*x[0]**2 - 3*x[1]**4 - 4*x[1]**3 - 4*x[1] + 3))/(x[0]**2 + x[1]**2 + 1)**3]])
grad = (G@J).T.reshape(2)
x = x + 0.1 * grad

In [1248]:
x

array([ 1.92078766e-05, -1.86851709e+00])