## My implementation of gradient descent on a sphere 


Important takeaway:

To keep dimensions when multiplying vectors 
np.tensor(a,b, 0)


for matrices matmul and dot

### dot simply does the dot product

A , shape(A) = (2,3,3) and 

B,  shape(B) = (2,3,3)

np.dot(A,B) = C, shape(C) = (2,3,2,3)

### Matmul function broadcasts the array like a stack of matrices 
np.matmul(A,B) = C , shape(C) = (2,3,3)

So it just considers like a stack of matrices where it multiplies "elementwise" along first x-2 dimensions (last two indices are multiplied over)
masically it's 
[ A[0] @ B[0], A[1] @ B[1] ]

In [156]:
import numdifftools as nd
import numpy as np

In [157]:
np.random.seed(42)
A = np.random.normal(size=(3, 3))
A = 0.5 * (A + A.T)

In [158]:
myfcn = lambda X: -X @ A @ X

In [159]:
def mygrad(X):
	return (np.eye(3) - np.tensordot(X, np.transpose(X),0)) @ nd.Gradient(myfcn)(X)

In [160]:
X  = np.array([1, 0, 0 ])

In [161]:
lr = 0.1
for i in range(500):
	if i%100==0:
		lr = lr/10
	V = -lr * mygrad(X)
	X=X+V
	X = X/np.linalg.norm(X)

In [163]:
eigenvalues, eigenvectors = np.linalg.eig(A)
dominant_eigenvector = eigenvectors[:, eigenvalues.argmax()]
print(f"My solution is {X}")
print(f"Real is {dominant_eigenvector}")

My solution is [0.78578684 0.37956989 0.48832954]
Real is [-0.78442334 -0.38225031 -0.48843088]


In [165]:
np.dot(X,X)

1.0

In [166]:
a = np.random.rand(2,3,3)
b = np.random.rand(2,3,3)

In [167]:
np.matmul(a,b)

array([[[0.36826431, 0.3623116 , 0.23061871],
        [0.58258805, 0.75769542, 0.58445169],
        [0.35246349, 0.75165831, 0.64010223]],

       [[0.70778062, 0.74401894, 0.62044564],
        [0.5400433 , 0.6714374 , 0.45137049],
        [0.26890576, 0.49733666, 0.26313891]]])

In [169]:
a[0] @ b[0]

array([[0.36826431, 0.3623116 , 0.23061871],
       [0.58258805, 0.75769542, 0.58445169],
       [0.35246349, 0.75165831, 0.64010223]])

In [170]:
a[1] @ b[1]

array([[0.70778062, 0.74401894, 0.62044564],
       [0.5400433 , 0.6714374 , 0.45137049],
       [0.26890576, 0.49733666, 0.26313891]])